CXX = g++
CXXFLAGS = -std=c++17 -O2
INCLUDES = -I. -I/usr/include/opencv4
LIBS = -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui

SOURCES = analyze_image_quality.cpp \
          GRADIENT_BASED_OPTIMIZER/src/image_metrics.cpp \
          GRADIENT_BASED_OPTIMIZER/src/embedding_schemes.cpp \
          GRADIENT_BASED_OPTIMIZER/src/gbo.cpp \
          GRADIENT_BASED_OPTIMIZER/src/population.cpp \
          GRADIENT_BASED_OPTIMIZER/src/random_utils.cpp \
          GRADIENT_BASED_OPTIMIZER/src/block_metrics.cpp \
          GRADIENT_BASED_OPTIMIZER/src/image_processing_custom.cpp

quality_analyzer: $(SOURCES)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o quality_analyzer $(SOURCES) $(LIBS)

clean:
	rm -f quality_analyzer image_quality_report.txt

.PHONY: clean